//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_kho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceState
    {
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
