//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Quan_ly_kho.Models;

//namespace System
//{
//    partial class Document
//    {
//        public int FloorId { get => GetValue<int>(nameof(FloorId)); set => Push(nameof(FloorId), value); }
//        public string RoomNumber { get => GetString(nameof(RoomNumber)); set => Push(nameof(RoomNumber), value); }
//        public virtual Floor Floor { get => GetObject<Floor>(nameof(Floor)); set => Push(nameof(Floor), value); }
//    }
//}


namespace Quan_ly_kho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room 
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Room()
        //{
        //    this.Device = new HashSet<Device>();
        //}

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Device> Device { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Device = new HashSet<Device>();
        }

        public int Id { get; set; }
        public int FloorId { get; set; }
        public string RoomNumber { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
        public virtual Floor Floor { get; set; }
    }

}
