//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Quan_ly_kho.Models;

//namespace System
//{
//    partial class Document
//    {
        
//    }
//}

namespace Quan_ly_kho.Models
{
    using Quan_ly_kho.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule : BaseViewModel
    {
        //public System.DateTime StartTime { get; set; }
        //public System.DateTime EndTime { get; set; }
        //public string Action { get; set; }

        public int Id { get; set; }
        public int DeviceId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Action { get; set; }

        public virtual Device Device { get; set; }
    }
    public partial class Schedule
    {
        private string _scheduleDescription;
        public string ScheduleDescription
        {
            set 
            { 
                _scheduleDescription = value;
                OnPropertyChanged();
            }
            get
            {
                return $"{StartTime:dd/MM/yyyy HH:mm} - {EndTime:dd/MM/yyyy HH:mm}";
            }
        }
    }
}
