//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Quan_ly_kho.Models;

namespace System
{
    partial class Document
    {
        
    }
}

namespace Quan_ly_kho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule : Document
    {
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Action { get; set; }
    }
    public partial class Schedule
    {
        public string ScheduleDescription
        {
            get
            {
                return $"{StartTime:dd/MM/yyyy HH:mm} - {EndTime:dd/MM/yyyy HH:mm}";
            }
        }
    }
}
