//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Quan_ly_kho.Models;

namespace System
{
    partial class Document
    {
        public int Id { get => GetValue<int>(nameof(Id)); set => Push(nameof(Id), value); }
        public string Username { get => GetString(nameof(Username)); set => Push(nameof(Username), value); }
        public string PasswordHash { get => GetString(nameof(PasswordHash)); set => Push(nameof(PasswordHash), value); }
        public int RoleId { get => GetValue<int>(nameof(RoleId)); set => Push(nameof(RoleId), value); }
        public virtual Role Role { get => GetObject<Role>(nameof(Role)); set => Push(nameof(Role), value);}
    }
}

namespace Quan_ly_kho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : Document
    {
        
    }
    public partial class User
    {
        public User(string name, string password)
        {
            Username = name;
            PasswordHash = (name + password).ToMD5();
        }
    }

}
